#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend creator_backend
        balance roundrobin
        server 407355-web-01 52.201.211.179:80 check
        server 407355-web-02 54.157.165.107:80 check
frontend creator_frontend
        bind *:80
        mode http
        default_backend creator_backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
